"""Deterministic Python stub generator.

The spec already contains everything needed to produce a typed function
signature and a docstring. Generating this with an LLM would be slower,
costlier, and less reliable than just templating it. The assignment
explicitly says "a mock implementation is fine".
"""

from __future__ import annotations

from src.schema import ToolSpec


_JSON_TO_PY = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "array": "list",
    "object": "dict",
}


def generate_stub(spec: ToolSpec) -> str:
    """Render a Python function stub from a ToolSpec.

    Required params have no default. Optional params get `= None`
    and are typed as `Optional[...]`. The docstring follows Google style.
    """
    # Order: required first (no default), then optional (with default).
    # Python requires this — non-default arg can't follow default arg.
    required = [p for p in spec.parameters if p.required]
    optional = [p for p in spec.parameters if not p.required]

    has_optional = bool(optional)
    arg_lines: list[str] = []
    for p in required:
        arg_lines.append(f"    {p.name}: {_JSON_TO_PY[p.type]},")
    for p in optional:
        arg_lines.append(f"    {p.name}: {_JSON_TO_PY[p.type]} | None = None,")

    args_block = "\n".join(arg_lines) if arg_lines else ""

    doc_args: list[str] = []
    for p in required + optional:
        doc_args.append(f"        {p.name}: {p.description}")
    doc_args_block = "\n".join(doc_args) if doc_args else "        (no parameters)"

    return f'''"""Mock stub generated by Tool Discoverer for {spec.name}."""

from __future__ import annotations


def {spec.name}(
{args_block}
) -> dict:
    """{spec.description}

    Args:
{doc_args_block}

    Returns:
        {spec.return_schema.description}
    """
    raise NotImplementedError(
        "This is a mock stub generated by the Tool Discoverer. "
        "Real implementation should call the underlying service or compute the result."
    )
'''
